Write-Host ''
Write-Host 'Welcome on Tweetinvi, please see the documentation at : https://tweetinvi.codeplex.com/documentation'
Write-Host 'You can also get lots of examples from the Cheatsheet provided with this package : Cheatsheet.cs'
Write-Host ''
Write-Host 'EXAMPLE : Get the currently logged in user:'
Write-Host ''
Write-Host 'TwitterCredentials.SetCredentials("ACCESS_TOKEN", "ACCESS_TOKEN_SECRET", "CONSUMER_KEY", "CONSUMER_SECRET");'
Write-Host 'var user = User.GetLoggedUser();'
Write-Host 'Debug.WriteLine(user.ScreenName);'
Write-Host ''
Write-Host 'Please enjoy Tweetinvi!'