using Tweetinvi.Core.Attributes;

namespace Tweetinvi.Models
{
    /// <summary>
    /// Languages available as filters for Search and Streams.
    /// </summary>
    public enum LanguageFilter
    {
        [Language("Amharic", "am")] Amharic,
        [Language("Arabic", "ar")] Arabic,
        [Language("Armenian", "hy")] Armenian,
        [Language(new[] { "Bengali", "Bangla" }, "bn")] Bengali,
        [Language("Bosnian", "bs")] Bosnian,
        [Language("Bulgarian", "bg")] Bulgarian,
        [Language("Burmese", "my")] Burmese,
        [Language("Central Kurdish", "ckb")] CentralKurdish,
        [Language("Chinese", "zh")] Chinese,
        [Language("Croatian", "hr")] Croatian,
        [Language("Danish", "da")] Danish,
        [Language("Dutch", "nl")] Dutch,
        [Language("English", "en")] English,
        [Language("Estonian", "et")] Estonian,
        [Language("Finnish", "fi")] Finnish,
        [Language("French", "fr")] French,
        [Language("Georgian", "ka")] Georgian,
        [Language("German", "de")] German,
        [Language(new[] { "Greek", "Modern Greek" }, "el")] Greek,
        [Language("Gujarati", "gu")] Gujarati,
        [Language(new[] { "Hebrew", "Ivrit" }, "he", "iw")] Hebrew,
        [Language("Hindi", "hi")] Hindi,
        [Language("Hungarian", "hu")] Hungarian,
        [Language("Icelandic", "is")] Icelandic,
        [Language("Indonesian", "id", "in")] Indonesian,
        [Language("Italian", "it")] Italian,
        [Language("Japanese", "ja", "jp")] Japanese,
        [Language("Kannada", "kn")] Kannada,
        [Language("Khmer", "km")] Khmer,
        [Language("Korean", "ko")] Korean,
        [Language("Lao", "lo")] Lao,
        [Language("Latvian", "lv")] Latvian,
        [Language("Lithuanian", "lt")] Lithuanian,
        [Language("Malayalam", "ml")] Malayalam,
        [Language("Marathi", "mr")] Marathi,
        [Language("Nepali", "ne")] Nepali,
        [Language("Norwegian", "no")] Norwegian,
        [Language(new[] { "Oriya", "Odia" }, "or")] Oriya,
        [Language(new[] { "Pashto", "Pushto" }, "ps")] Pashto,
        [Language(new[] { "Persian", "Farsi" }, "fa")] Persian,
        [Language("Polish", "pl")] Polish,
        [Language("Portuguese", "pt")] Portuguese,
        [Language(new[] { "Punjabi", "Panjabi" }, "pa")] Punjabi,
        [Language("Romanian", "ro")] Romanian,
        [Language("Russian", "ru")] Russian,
        [Language("Sindhi", "sd")] Sindhi,
        [Language(new[] { "Sinhala", "Sinhalese" }, "si")] Sinhala,
        [Language("Slovak", "sk")] Slovak,
        [Language("Slovenian", "sl")] Slovenian,
        [Language(new[] { "Spanish", "Castilian" }, "es")] Spanish,
        [Language("Swedish", "sv")] Swedish,
        [Language("Tagalog", "tl")] Tagalog,
        [Language("Tamil", "ta")] Tamil,
        [Language("Telugu", "te")] Telugu,
        [Language("Thai", "th")] Thai,
        [Language("Turkish", "tr")] Turkish,
        [Language("Urdu", "ur")] Urdu,
        [Language(new[] { "Uyghur", "Uighur" }, "ug")] Uyghur,
        [Language("Vietnamese", "vi")] Vietnamese,
    }
}