using System.Threading.Tasks;

namespace Tweetinvi.Client
{
    public interface IAuthClient
    {
        /// <summary>
        /// Allows a registered application to obtain an OAuth 2 Bearer Token.
        /// Bearer token allows to make API requests on an application's own behalf, without a user context.
        /// This is called Application-only authentication.
        /// </summary>
        /// <para> https://developer.twitter.com/en/docs/basics/authentication/api-reference/token </para>
        /// <returns>The bearer token to use for application only authentication</returns>
        Task<string> CreateBearerToken();

        /// <summary>
        /// Gets the bearer token generated by <see cref="CreateBearerToken"/> and updates the client's current credentials.
        /// To learn more about bearer token read <see cref="CreateBearerToken"/>.
        /// </summary>
        /// <para> IMPORTANT NOTE: The setter is for convenience. It is strongly recommended to create a new TwitterClient instead.
        /// As using this setter could result in unexpected concurrency between the time of set and the execution of previous
        /// non awaited async operations. </para>
        /// <para> https://developer.twitter.com/en/docs/basics/authentication/api-reference/token </para>
        Task InitializeClientBearerToken();
    }
}