using System.Threading.Tasks;
using Tweetinvi.Auth;
using Tweetinvi.Models;
using Tweetinvi.Parameters.Auth;

namespace Tweetinvi.Client
{
    public interface IAuthClient
    {
        /// <summary>
        /// Allows a registered application to obtain an OAuth 2 Bearer Token.
        /// Bearer token allows to make API requests on an application's own behalf, without a user context.
        /// This is called Application-only authentication.
        /// </summary>
        /// <para> https://developer.twitter.com/en/docs/basics/authentication/api-reference/token </para>
        /// <returns>The bearer token to use for application only authentication</returns>
        Task<string> CreateBearerToken();

        /// <summary>
        /// Gets the bearer token generated by <see cref="CreateBearerToken"/> and updates the client's current credentials.
        /// To learn more about bearer token read <see cref="CreateBearerToken"/>.
        /// </summary>
        /// <para>
        /// IMPORTANT NOTE: The setter is for convenience. It is strongly recommended to create a new TwitterClient instead.
        /// As using this setter could result in unexpected concurrency between the time of set and the execution of previous
        /// non awaited async operations.
        /// </para>
        /// <para> https://developer.twitter.com/en/docs/basics/authentication/api-reference/token </para>
        Task InitializeClientBearerToken();

        /// <summary>
        /// Initiates a pin based authentication process for a user.
        /// The AuthenticationContext returned contains a url to authenticate on twitter.
        /// </summary>
        /// <para> https://developer.twitter.com/en/docs/basics/authentication/api-reference/request_token </para>
        /// <returns>An AuthenticationContext containing both the url to redirect to and an AuthenticationToken</returns>
        Task<IAuthenticationRequestToken> RequestAuthenticationUrl();

        /// <inheritdoc cref="RequestAuthenticationUrl" />
        Task<IAuthenticationRequestToken> RequestAuthenticationUrl(string redirectUrl);

        /// <inheritdoc cref="RequestAuthenticationUrl" />
        Task<IAuthenticationRequestToken> RequestAuthenticationUrl(string redirectUrl, IAuthenticationTokenProvider authenticationTokenProvider);

        /// <summary>
        /// Initiates the authentication process for a user.
        /// The AuthenticationContext returned contains a url to authenticate on twitter.
        /// </summary>
        /// <para> https://developer.twitter.com/en/docs/basics/authentication/api-reference/request_token </para>
        /// <returns>An AuthenticationContext containing both the url to redirect to and an AuthenticationToken</returns>
        Task<IAuthenticationRequestToken> RequestAuthenticationUrl(IRequestAuthUrlParameters parameters);

        /// <summary>
        /// Request credentials from an AuthenticationTokenProvider.
        /// This is assuming that the callback url contains the expected parameter,
        /// and that the AuthenticationTokenProvider has access to the returned token id.
        /// </summary>
        /// <para> https://developer.twitter.com/en/docs/basics/authentication/api-reference/request_token </para>
        /// <returns>The requested user credentials</returns>
        Task<ITwitterCredentials> RequestCredentialsFromCallbackUrl(string callbackUrl, IAuthenticationTokenProvider authenticationTokenProvider);

        /// <summary>
        /// Request credentials from an AuthenticationToken.
        /// This is assuming that the callback url contains the expected parameter,
        /// and that the AuthenticationTokenProvider has access to the returned token id.
        /// </summary>
        /// <para> https://developer.twitter.com/en/docs/basics/authentication/api-reference/request_token </para>
        /// <returns>The requested user credentials</returns>
        Task<ITwitterCredentials> RequestCredentialsFromCallbackUrl(string callbackUrl, IAuthenticationRequestToken authenticationRequestToken);

        /// <inheritdoc cref="RequestCredentials(IRequestCredentialsParameters)"/>
        Task<ITwitterCredentials> RequestCredentials(string verifierCode, IAuthenticationRequestToken authenticationRequestToken);

        /// <summary>
        /// Request credentials with a verifierCode
        /// </summary>
        /// <para> https://developer.twitter.com/en/docs/basics/authentication/api-reference/request_token </para>
        /// <returns>The requested user credentials</returns>
        Task<ITwitterCredentials> RequestCredentials(IRequestCredentialsParameters parameters);
    }
}