Write-Host ''
Write-Host 'Welcome on Tweetinvi, please read the documentation on https://github.com/linvi/tweetinvi/wiki'
Write-Host 'You can also get lots of examples from the Cheatsheet provided with this package : Cheatsheet.cs'
Write-Host ''
Write-Host 'EXAMPLE : Get the currently authenticated user:'
Write-Host ''
Write-Host 'var client = new TwitterClient("ACCESS_TOKEN", "ACCESS_TOKEN_SECRET", "CONSUMER_KEY", "CONSUMER_SECRET");'
Write-Host 'var user = await client.Users.GetAuthenticatedUserAsync();'
Write-Host 'Debug.WriteLine(user.ScreenName);'
Write-Host ''
Write-Host 'Enjoy Tweetinvi!'