Write-Host ''
Write-Host 'Welcome on Tweetinvi, please read the documentation at : https://github.com/linvi/tweetinvi/wiki'
Write-Host 'You can also get lots of examples from the Cheatsheet provided with this package : Cheatsheet.cs'
Write-Host ''
Write-Host 'EXAMPLE : Get the currently logged in user:'
Write-Host ''
Write-Host 'Auth.SetUserCredentials("CONSUMER_KEY", "CONSUMER_SECRET", "ACCESS_TOKEN", "ACCESS_TOKEN_SECRET");'
Write-Host 'var user = User.GetLoggedUser();'
Write-Host 'Debug.WriteLine(user.ScreenName);'
Write-Host ''
Write-Host 'Please enjoy Tweetinvi!'